# Generated by Django 4.2.8 on 2023-12-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagename', models.TextField()),
                ('articleimage', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='photo',
            field=models.ManyToManyField(blank=True, related_name='photos', to='mainapp.photo'),
        ),
    ]
