# Generated by Django 4.2.8 on 2023-12-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_photo_car_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ManyToManyField(related_name='photos', to='mainapp.photo'),
        ),
    ]
