# Generated by Django 4.2.8 on 2024-01-05 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_myuser_options_alter_myuser_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='login',
        ),
    ]
