# Generated by Django 4.2.8 on 2024-01-05 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_remove_myuser_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(default='', max_length=60, unique=True, verbose_name='Логин'),
        ),
    ]
